# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calories Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'
  pod 'MKMagneticProgress'
  pod 'MKColorPicker'
  pod 'Charts'

  # Pods for Calories Counter

end
